[package]
name = "puddle-core"
version = "0.1.0"
authors = ["Max Willsey <me@mwillsey.com>"]

[dependencies]

rand = "^0.5.0-pre.0"

serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"

jsonrpc-core = "^8.0.1"
jsonrpc-macros = "^8.0.0"

rouille = "^2.0"

clap = "^2.29.4"
log = "^0.4.1"

crossbeam = "0.3.2"
env_logger = "^0.5.3"

# union-find
ena = "^0.9.2"

[dev-dependencies]
glob = "^0.2"