[package]
name = "puddle-core"
version = "0.1.0"
authors = ["Max Willsey <me@mwillsey.com>"]

[dependencies]

rand = "^0.4"

serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
lazy_static = "^1.0"

rouille = "^2.0"

jsonrpc-core = "^8.0.1"
jsonrpc-macros = "^8.0.0"

clap = "^2.29.4"

[dev-dependencies]
proptest = "^0.4"
glob = "^0.2"